services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    command: server --console-address ":9001" /data
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: P@ssw0rd
    ports:
      - protocol: tcp
        published: 9000
        target: 9000
      - protocol: tcp
        published: 9001
        target: 9001
    volumes:
      - ./volume/data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5